### ISSUE TITLE
videobridge is not able to connect to Prosody, jibri does not work at all and breaks functionality to join rooms

### ISSUE THREAD

**Issue by renepardon** [udima-university/ansible-jitsi-meet#7]
I've an easy setup with Jitsi Meet, Jibri Server and videobridge but a bunch of errors.

When all playbooks were executed successfully, on JVB I see:

**/var/log/jitsi/jvb.log**
<details>

```bash
2020-12-20 17:21:36.143 INFO: [17] [hostname=XXX.XXX.XXX.XXX id=shard] MucClient.lambda$getConnectAndLoginCallable$7#680: Logging in.
2020-12-20 17:21:36.144 SEVERE: [17] RetryStrategy$TaskRunner.run#198: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.lang.Thread.run(Thread.java:748)
```
</details>

**/var/log/jitisi/jicofo.log**

<details>

```bash
Jicofo 2020-12-20 17:32:15.868 INFO: [53] org.jitsi.jicofo.xmpp.FocusComponent.log() Focus request for room: 18fea7e6-f274-43b1-b29f-b30de9407513@conference.XXX.XXX.XXX
Jicofo 2020-12-20 17:32:16.075 INFO: [91] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@6749fb98 member=ChatMember[18fea7e6-f274-43b1-b29f-b30de9407513@conference.XXX.XXX.XXX/dd25644b, jid: null]@803911713]
Jicofo 2020-12-20 17:32:16.075 INFO: [91] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member 18fea7e6-f274-43b1-b29f-b30de9407513@conference.XXX.XXX.XXX/dd25644b joined.
Jicofo 2020-12-20 17:32:16.076 SEVERE: [91] org.jitsi.jicofo.JitsiMeetConfig.log() Error parsing: startAudioMuted, v: false
Jicofo 2020-12-20 17:32:16.076 WARNING: [91] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-12-20 17:32:16.076 SEVERE: [91] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
```

</details>

**/var/log/prosody/prosody.{log,err}**

<details>

```bash
Dec 20 17:34:00 conference.XXX.XXX.XXX:muc_domain_mapper	warn	Session filters applied
Dec 20 17:34:00 mod_bosh	info	New BOSH session, assigned it sid 'c9128612-6532-40d7-9265-faacd6e01c28'
Dec 20 17:34:01 boshc9128612-6532-40d7-9265-faacd6e01c28	info	Authenticated as d70a618f-cf24-464e-b777-12b67cd45ee6@XXX.XXX.XXX
```

</details>

I also came across https://github.com/jitsi/jitsi-meet/issues/3639 and disabled bosh to listen on HTTPS.
If I enable "recording" there is an additional problem with Jibri and the included presence_identity module. See: https://github.com/jitsi/jitsi-meet/issues/8284

**Comment by inittab** [comment]
Hi, Christoph. I'm not sure what could have happened, but the authentication configuration in the videobridge does not match the one in prosody. You should check it is OK (matching) in /etc/jitsi/videobridge/sip-communicator.properties and /var/lib/prosody/..../accounts/your_videobridge.dat.
